import rhinoscriptsyntax as rsimport os#Script written by Eric Werner, (c) 2011__commandname__ = "CommandName"  def RunCommand( is_interactive ):    print "executing ", __commandname__       gObjs = rs.GetObjects('Select Objects to export')    method = rs.GetString('How to export the objects?', 'byLayer', ['byLayer', 'Enumerate'])    type = rs.GetString('File extension?', '.3dm', ['.3dm', '.sat', '.dwg'])        if os.name == 'nt':     	path = 'c:\\temp\\'    else:    	path = '/Users/ericwerner/Desktop/'    	    #rs.BrowseForFolder(folder=None, message="Set folder to Export to:", title="Export location")       lnames  = []       rs.EnableRedraw(False)       if gObjs:        if method == 'byLayer':                       for obj in gObjs:                lnames.append(rs.ObjectLayer(obj))            lnames = list(set(lnames))            print lnames            for name in lnames:                rs.UnselectAllObjects()                oList = []                for obj in gObjs:                    if rs.ObjectLayer(obj) == name:                        oList.append(obj)                rs.UnselectAllObjects()                rs.SelectObjects(oList)                               rs.Command('-Export Version=5 SaveSmall=No GeometryOnly=Yes SaveTextures=No SavePluginData=No ' + path + name.replace(" ", "") + type + " Enter ")                    else:            for name, obj in enumerate(gObjs):                rs.UnselectAllObjects()                rs.SelectObject(obj)                rs.Command('-Export Version=5 SaveSmall=No GeometryOnly=Yes SaveTextures=No SavePluginData=No ' + path + str(name) + type + " Enter ")                    rs.UnselectAllObjects()       rs.EnableRedraw(True)           return 0 # this will be called if not being run as a commandif( __name__=="__main__" ):    RunCommand(True)